### ISSUE TITLE
Kernel compiled with the latest source code cannot start

### ISSUE THREAD

**Issue by Boom-Hacker** [crdroidandroid/android_kernel_oneplus_sdm845#2]
System Environment:Arch Linux (linux-zen 6.2)
build command:
git clone https://github.com/crdroidandroid/android_kernel_oneplus_sdm845
cd android_kernel_oneplus_sdm845
export ARCH=arm64
export CC=clang
export CROSS_COMPILE
export LLVM=1
make O=out enchilada_defconfig
make O=out -j12

Please compile and start the kernel in the official way to see if it starts properly

**Comment by Terminator-J** [comment]
It compiles but doesn't boot?
Or it doesn't compile?

Also, which clang version are you using?
You might need to revert one or more of the following commits to compile successfully on clang 14 or earlier:
eda842f329675cba5372f9a76d39acea7ad6067b "qcacld-3.0: [hax] Fix compilation under clang 16"
ed0d96c231d184485a09fb3183f9db28237d6db4 "ipa_v3: [hax] Fix compilation under clang 16"
76505ca1844501d81b10e3709b9371161ae7fc22 "Makefile: Temporarily disable warning / error void-ptr-dereference with latest Clang-16"

Also, if you have not removed the virtual framebuffer kernel commandline argument from BoardConfigCommon.mk in your sdm845-common tree, then you might run into trouble since I removed the virtual fb from the kernel defconfig as well.
Revert 8d873ab07cc15b493856a519fd9eae7f8cc768b3 "configs: Remove virtual framebuffer" to reenable the capability.

**Comment by gwolf2u** [comment]
lack of feedback, so closing this
